### ISSUE TITLE
Does not create firewall rules in eviroments

### ISSUE THREAD

**Issue by rmalenko** [alexharv074/puppet-firewall_multi#18]
Hi, again Alex :)
Thank you a lot for this module. I am sure I do something wrong and it isn't an issue.
This module works for production environment but does not work for stage and rnd
Could you be so kindly help to resove it, please?

My hiera.yaml
```
---
version: 5
defaults:
environments.
  datadir: "/etc/puppetlabs/code/environments"
  data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    path: "%{::environment}/nodes/%{::trusted.certname}.yaml"
  - name: "Common YAML hierarchy levels"
    paths:
      - "defaults/common.yaml"
      - "defaults/users.yaml"
      - "defaults/users_groups.yaml"
      - "defaults/sudo.yaml"
      - "defaults/firewall.yaml"
      - ...
      - "defaults/ntp.yaml"
  - name: "Common for an environment hierarchy levels"
    paths:
      - "%{::environment}/common.yaml"
      - "%{::environment}/users.yaml"
```
site.pp
```
class myclass (
  Hash[String, Hash] $firewall_multis,
) {
  $firewall_multis.each |$name, $firewall_multi| {
    firewall_multi { $name:
      * => $firewall_multi
    }
  }
  ...
}
```
firewall.yaml
```
---
myclass::firewall_multis:
  '00099 accept tcp port 22 for ssh':
    dport: '22'
    action: 'accept'
    proto: 'tcp'
    source:
      - 1.1.1.1
      - 18.21.1.6/24
```

```
├── defaults
│   ├── apt.yaml
│   ├── common.yaml
│   ├── firewall.yaml
│   ├── ntp.yaml
│   ├── packages.yaml
│   ├── puppet.yaml
│   ├── ssh.yaml
│   ├── sudo.yaml
│   ├── users_groups.yaml
│   └── users.yaml
├── production
│   ├── common.yaml
│   ├── environment.conf
│   ├── manifests
│   │   └── site.pp
│   ├── modules
│   ├── nodes
│   │   ├── puppetmaster.biz.yaml
│   └── users.yaml
├── rnd
│   ├── common.yaml
│   ├── environment.conf
│   ├── manifests
│   │   └── site.pp
│   ├── modules
│   ├── nodes
│   │   └── puppet-slv-01.biz.yaml
└── stage
...
```
