### ISSUE TITLE
Error: no parameter named 'ipvs'

### ISSUE THREAD

**Issue by rmalenko** [alexharv074/puppet-firewall_multi#19]
Hi Alex,
I have got this error after upgrade module

```Error: no parameter named 'ipvs' (file: /etc/puppetlabs/code/modules/firewall_multi/manifests/init.pp, line: 257) on Firewall[001 accept all icmp] (file: /etc/puppetlabs/code/modules/firewall_multi/manifests/init.pp, line: 257) on node m```

Regards,
Rostyslav

**Comment by alexharv074** [comment]
Hi @rmalenko , it looks like you upgraded my module without also updating the upstream puppetlabs/firewall module? See the latest commit [here](https://github.com/alexharv074/puppet-firewall_multi/commit/5ffbf6d24f97e04ddd10a9a6d93a86d17596e683). Let me know if that fixes your issue.

**Comment by rmalenko** [comment]
I have cloned just now alexharvey-firewall_multi (v1.13.0)
and upgrade to puppetlabs-firewall (v1.15.3)
but the error still remained

**Comment by mrmikeace** [comment]
I have a similar problem - although my error is different:
Server Error: no parameter named 'bytecode' 

I have tried using firewall_multi(v1.13.0) with firewall (v1.15.3), and firewall_multi(v1.12.0) with firewall (v1.15.1), same results.

**Comment by mrmikeace** [comment]
I even tried v1.11 of firewall_multi and v1.14 of firewall, and received a different error: 
no parameter named 'dst_cc' 

Very curious.

**Comment by alexharv074** [comment]
@rmalenko , @mrmikeace  It is curious because I can't reproduce any of these errors. Certainly, bytecode and ipvs are both parameters introduced in very recent versions of the firewall module. The dst_cc was added back in Oct 2017 in firewall v1.9.0. I'll need to know more info such as the version of Puppet you're using, a minimal, complete example for reproducing the error and so on.

**Comment by rmalenko** [comment]
`puppet --version 6.4.0`

site.pp
```
class firewallmulti (
  Hash[String, Hash] $firewall_multis,
) {
  $firewall_multis.each |$name, $firewall_multi| {
    firewall_multi { $name:
      * => $firewall_multi
    }
  }
}
```

firewall.yaml

```
---
classes:
  - firewallmulti
globalwhitelist:
  - 4.15.7.33   # masterofpuppet
  - ...

firewallmulti::firewall_multis:
  "001 accept all icmp":
    proto: "icmp"
    action: "accept"

  "002 accept all to lo interface":
    proto: "all"
    iniface: "lo"
    action: "accept"

  "003 reject local traffic not on loopback interface":
    iniface: "! lo"
    proto: "all"
    destination: "127.0.0.1/8"
    action: "reject"

  "004 accept inbound SSH":
    source:
      - "0.0.0.0/32"
      - "8.3.13.6/32"
    proto: "tcp"
    dport: "22"
    action: "accept"

  "005 Global whitelist":
    proto: "all"
    action: "accept"
    source: "%{alias('globalwhitelist')}"

  "006 accept related established rules":
    proto: "all"
    state: ["RELATED", "ESTABLISHED"]
    action: "accept"

  "999 accept related established rules":
    proto: "all"
    action: "drop"
```
