### ISSUE TITLE
Trying to wrap firewall_mutli with create_resources and a hiera_hash

### ISSUE THREAD

**Issue by robert4man** [alexharv074/puppet-firewall_multi#6]
I'm trying to wrap this with a hiera hash and a create resource so these can be defined in hiera, but I'm getting: Error 400 on SERVER: exception object expected

In my profile class I have:

```puppet
    $multi_rules = hiera_hash('firewall_multisource', '')
    if $multi_rules {
      create_resources('::firewall_mutli', $multi_rules)
    }
```

In a test node yaml I have:

```yaml
firewall_multisource:
  '570 lsnr 1234':
    dport: 1234
    source:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
  '570 lsnr 1235':
    dport: 1235
    source:
      - 192.168.0.1
      - 192.168.0.2
      - 192.168.0.3
      - 192.168.0.4
```

Not quite sure what I'm doing wrong, or if this is even possible.

**Comment by alexharv074** [comment]
Aside from some typos that's pretty much how I use it too.  What version of Puppet are you using?

**Comment by alexharv074** [comment]
I just tried your code on Puppet 4 & 3.8.6 and it's working fine for me:

- /tmp/foo.pp

```puppet
$multi_rules = hiera_hash('firewall_multisource', '')
if $multi_rules {
  create_resources('::firewall_multi', $multi_rules)
}
```

- /var/lib/hiera/common.yaml

```yaml
---
firewall_multisource:
  '570 lsnr 1234':
    dport: 1234
    source:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
  '570 lsnr 1235':
    dport: 1235
    source:
      - 192.168.0.1
      - 192.168.0.2
      - 192.168.0.3
      - 192.168.0.4
```

- puppet apply

```
Notice: Compiled catalog for centos-72-x64.home in environment production in 0.11 seconds
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1235]/Firewall[570 lsnr 1235 from 192.168.0.3]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1235]/Firewall[570 lsnr 1235 from 192.168.0.1]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1235]/Firewall[570 lsnr 1235 from 192.168.0.2]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1235]/Firewall[570 lsnr 1235 from 192.168.0.4]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1234]/Firewall[570 lsnr 1234 from 10.10.10.10]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1234]/Firewall[570 lsnr 1234 from 10.10.10.12]/ensure: created
Notice: /Stage[main]/Main/Firewall_multi[570 lsnr 1234]/Firewall[570 lsnr 1234 from 10.10.10.11]/ensure: created
Notice: Finished catalog run in 0.91 seconds
```
